### ISSUE TITLE
TagSelectorV2 - added tags do not get added?

### ISSUE THREAD

**Issue by ankidoc** [DarkTrick/AnkiTagSelector#3]
Hello!

I was using this add on on Anki 2.1.45. When I add tags in the tag list, and then activated them so the are display in the tag line, that are not getting added after creating a card. When I add a blank after the tag, then it gets recognized. I tried disabeling all add ons instead of this in case of add on interference, but nothing helps. Other add ons like "quick tagging" work. There is no error message, it's just not getting added. Thanks!

**Comment by DarkTrick** [comment]
Fixed with [version 24.6.3.1](https://github.com/DarkTrick/AnkiTagSelector/releases/tag/v24.6.3.1).
