### ISSUE TITLE
Running latest anki on ubuntu

### ISSUE THREAD

**Issue by SiddharthManthan** [DarkTrick/AnkiTagSelector#6]
Kindly download the latest anki for linux from the website. It is a tar archive which contains all the necessary dependencies. This way the latest anki can be run on old Ubuntu.

What specific version of Ubuntu are you using ?

**Comment by DarkTrick** [comment]
I'm not sure where this question is heading.

**Comment by anarchy1923** [comment]
Oh I think the guys is referring to the add-on page which starts with having problem for a specific version because the dev isn't able to run that version on ubuntu (yet). He's referring to how you could install the latest version through the tarball instead of relying on the flatpak or apt.
